import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/layout/Navbar";
import Main from "./Main";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#00ADB5]`}
			>
				<Toaster />
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					<div className="flex">
						<Navbar />
						<main className="h-dvh main-container-shadow  md:rounded-l-2xl sm:ml-2 bg-zinc-950 z-0 overflow-auto fixed top-0 w-full sm:w-[calc(100%-8rem)] md:w-[calc(100%-13rem)] right-0 origin-left scrollbar ">
							<Main>{children}</Main>
						</main>
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
